apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml
- ingress.yml

configMapGenerator:
- name: project-haha-config
  literals:
    - DATABASE_ENGINE=postgres
    - DATABASE_HOST=
    - DATABASE_PORT=5432
    - DATABASE_NAME=
    - SERVICE_PORT=80

commonLabels:
  app: project-haha
