apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deployable0504

resources:
  - namespace.yml

secretGenerator:
- name: deployable0504
  env: secrets.env

# Don't add a suffix to the secret name
generatorOptions:
  disableNameSuffixHash: true
